### ISSUE TITLE
"Property '__experimental__naiveDimensions' does not exist on type 'LenisOptions" when upgrading Typescript to 5.1.6

### ISSUE THREAD

**Issue by FlekaSukovicM** [darkroomengineering/lenis#309]
**Describe the bug**
I am in the process of upgrading from Angular v15 to v16, and I had to upgrade Typescript to 5.16 in this process. This caused Lenis library to not compile with the following error:

> Property '__experimental__naiveDimensions' does not exist on type 'LenisOptions'.

> constructor({ wrapper, content, wheelEventsTarget, eventsTarget, smoothWheel, syncTouch, syncTouchLerp, touchInertiaMultiplier, duration, easing, lerp, infinite, orientation, gestureOrientation, touchMultiplier, wheelMultiplier, normalizeWheel, autoResize, __experimental__naiveDimensions, }?: LenisOptions);

Looking into `index.d.ts`, it is evident that `__experimental__naiveDimensions` is not a field of LenisOptions type. Not sure why this didn't raise an error earlier.

**Comment by clementroche** [comment]
I've added this option for experimental reasons, i guess i need an extra tweak to make it TS compliant

**Comment by clementroche** [comment]
this should be fixed in v1.0.40
